`timescale 1ns/1ps
// Isolated resource/protocol prototype, deliberately not in coco3_top.
// Requires management_cpu generated by scripts/generate_management_ip.tcl.
// No boot firmware is attached yet; this wrapper is for synthesis evaluation.
module management_prototype (
    input wire clk_50mhz,
    input wire reset,
    output wire uart_tx,
    output wire usb_cs_n,
    output wire usb_sck,
    output wire usb_mosi,
    input wire usb_miso,
    input wire usb_int_n,
    output wire usb_reset_n,
    output wire usb_vbus_en,
    input wire usb_overcurrent_n,
    output wire usb_irq_pending
);
    wire [31:0] address, write_data, read_data, usb_read_data;
    wire [3:0] byte_enable;
    wire read_strobe, write_strobe, ready, usb_ack;
    wire request = read_strobe || write_strobe;
    wire usb_select = address[31:8] == 24'hc00000;
    reg unmapped_ack;
    // Acknowledge unmapped accesses with zero rather than hanging the processor.
    // Full high-address decode prevents aliases into a future SD/mailbox bank.
    always @(posedge clk_50mhz)
        if (reset) unmapped_ack <= 0;
        else unmapped_ack <= request && !usb_select;
    assign ready = usb_ack || unmapped_ack;
    assign read_data = usb_ack ? usb_read_data : 32'b0;

    management_cpu cpu (
        .Clk(clk_50mhz), .Reset(reset), .IO_addr_strobe(),
        .IO_address(address), .IO_byte_enable(byte_enable),
        .IO_read_data(read_data), .IO_read_strobe(read_strobe),
        .IO_ready(ready), .IO_write_data(write_data),
        .IO_write_strobe(write_strobe), .UART_txd(uart_tx)
    );
    usb_host_spi usb (
        .clk(clk_50mhz), .reset(reset), .bus_valid(request && usb_select),
        .bus_write(write_strobe), .bus_addr(address[7:0]),
        .bus_wdata(write_data), .bus_wstrb(byte_enable),
        .bus_rdata(usb_read_data), .bus_ack(usb_ack), .irq(usb_irq_pending),
        .usb_cs_n(usb_cs_n), .usb_sck(usb_sck), .usb_mosi(usb_mosi),
        .usb_miso(usb_miso), .usb_int_n(usb_int_n),
        .usb_reset_n(usb_reset_n), .usb_vbus_en(usb_vbus_en),
        .usb_overcurrent_n(usb_overcurrent_n)
    );
endmodule
