param(
    [Parameter(Mandatory = $true)][string]$Binary,
    [Parameter(Mandatory = $true)][string]$Output
)
$ErrorActionPreference = 'Stop'
$bytes = [System.IO.File]::ReadAllBytes((Resolve-Path $Binary))
if ($bytes.Length -eq 0 -or $bytes.Length -gt 57344) { throw "Firmware size $($bytes.Length) is outside 1..57344 bytes" }
$words = [int][Math]::Ceiling($bytes.Length / 4.0)
$lines = @('// Generated by generate_rv32_program_header.ps1; do not edit.', "localparam [15:0] MANAGER_PROGRAM_WORDS = 16'd$words;", 'function [31:0] manager_program_word;', '    input [15:0] index;', '    begin', '        case (index)')
for ($word = 0; $word -lt $words; ++$word) {
    $offset = $word * 4
    [uint32]$value = 0
    for ($byte = 0; $byte -lt 4 -and ($offset + $byte) -lt $bytes.Length; ++$byte) {
        $value = $value -bor ([uint32]$bytes[$offset + $byte] -shl (8 * $byte))
    }
    $lines += ('            16''d{0}: manager_program_word = 32''h{1:X8};' -f $word, $value)
}
$lines += '            default: manager_program_word = 32''h00000013;', '        endcase', '    end', 'endfunction'
[System.IO.File]::WriteAllLines($Output, $lines)
